#!/bin/bash

ENV_FILE_PATH=".env"

echo "
FROM alpine:3
RUN apk add --no-cache openssh openssl && apk add --update coreutils
" | docker build -t localhost/generate-jwt-keys -

docker run -it -v ${PWD}/$ENV_FILE_PATH:/app/.env --rm localhost/generate-jwt-keys /bin/sh -c '
  ssh-keygen -t rsa -b 2048 -m PEM -P "" -f jwtRS256.key
  openssl rsa -in jwtRS256.key -pubout -outform PEM -out jwtRS256.key.pub

  sed "/^JWT_PUBLIC_KEY_BASE64=/s/=.*/=\"$(base64 -i -w 0 jwtRS256.key.pub)\"/" /app/.env > /tmp/.env; cp /tmp/.env /app/.env
  sed "/^JWT_PRIVATE_KEY_BASE64=/s/=.*/=\"$(base64 -i -w 0 jwtRS256.key)\"/" /app/.env > /tmp/.env; cp /tmp/.env /app/.env
  echo -e "\e[32m\e[1mJWT keys generated\e[0m"
'
